persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Porta padrão (para os códigos Node.js)
listener 1883
allow_anonymous true

# Porta WebSockets (para o Dashboard)
listener 9001
protocol websockets
allow_anonymous true